[package]
name = "stop_solver"
version = "0.1.0"
edition = "2021"
authors = ["Juan Manuel Young Hoyos"]

[dependencies]
reqwest = "0.11.6"
serde = "1.0.130"
serde_json = "1.0"
futures = "0.3"
tokio = { version = "1.14.0", features = ["full"] }